### Base URL
@baseUrl = http://localhost:5262/api/students

### 1. Add Student
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Rohan Kalkumbe",
  "age": 22,
  "course": "Computer Science",
  "phone" : "9049045218"
}

### 2. Get Students List
GET {{baseUrl}}

### 3. Get Student by ID
GET {{baseUrl}}/2

### 4. Update Student
PUT {{baseUrl}}/2
Content-Type: application/json

{
  "name": "Gayatri",
  "age": 22,
  "course": "Computer Science",
  "phone" : "9049045218"
}

### 5. Delete Student
DELETE {{baseUrl}}/3

### 6. Search Student by Name
GET {{baseUrl}}/search?name=Rohan%20Kalkumbe

### 7. Search Student by ID
GET {{baseUrl}}/search?id=2

